name: Build

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, "386"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.5"
      - name: Build
        run: go build
        env:
          GOOS: windows
          GOARCH: ${{ matrix.arch }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./cf-updater.exe
          asset_name: cf-updater-${{ matrix.arch }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable
